name: Kompiliere und update pdf
on: push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kompiliere LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Lade pdf hoch
        uses: actions/upload-artifact@v7
        with:
          name: PDF
          path: main.pdf